# Generated by Django 5.1.3 on 2024-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=56),
        ),
    ]
